version: "3"
services:

  postgres:
    image: 'postgres:14.11'
    container_name: local-postgre
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: on-failure

  redis:
    image: 'redis:5-alpine'
    command: redis-server
    container_name: local-redis
    ports:
      - 6379:6379
